# If false, no loadbalancer will be deployed
enabled: true
# API port for k8s (routed through the loadbalancer). define as eg. 7443 if you want to run loadbalancer and master on the same host
k8s_loadbalancer_api_port: 7443
# Define services with nodeports which will be exposed through the loadbalancer
exposed_services:

# Headlamp
- name: headlamp
  ports:
  - name: ssl
    sourceport: "{{ headlamp_config.nodeport | default(32443) }}"
    gatewayport: 8443

# Contour Ingress!
- name: contour
  ports:
  - name: ssl
    sourceport: "{{ contour_config.ssl_nodeport | default(30443) }}"
    gatewayport: 443
  - name: http
    sourceport: "{{ contour_config.http_nodeport | default(30080) }}"
    gatewayport: 80
