# Define services with nodeports which will be exposed through the loadbalancer
exposed_services:
# Kubernetes Dashboard
- name: kubernetes-dashboard
  ports:
  - name: ssl
    sourceport: "{{ kubernetes_dashboard_config.nodeport }}"
    gatewayport: 8443
# Contour Ingress!
- name: contour
  ports:
  - name: ssl
    sourceport: "{{ contour_config.ssl_nodeport }}"
    gatewayport: 443
  - name: http
    sourceport: "{{ contour_config.http_nodeport }}"
    gatewayport: 80