apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- whereabouts.cni.cncf.io_ippools.yaml
- daemonset-install.yaml
- whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml