- name: Read variable definitions
  hosts: "*, localhost"
  roles:
    - read_config_vars
- name: Upgrade master0
  hosts: "{{ groups.master[0] }}"
  serial: 1
  tasks:
    - name: Kick master0 upgrade
      ansible.builtin.include_tasks: roles/upgrade_cluster/tasks/master0.yml

- name: Upgrade masters except master0
  hosts: "{{ groups.master[1:] }}"
  serial: 1
  tasks:
    - name: Update the other masters
      ansible.builtin.include_tasks: roles/upgrade_cluster/tasks/masters.yml

- name: Upgrade workers
  hosts: "{{ groups.worker }}"
  serial: 1
  tasks:
    - name: Update workers
      ansible.builtin.include_tasks: roles/upgrade_cluster/tasks/workers.yml

- name: Finish on master0
  hosts: "{{ groups.master[0] }}"
  serial: 1
  tasks:
    - name: Finish on master0
      ansible.builtin.include_tasks: roles/upgrade_cluster/tasks/finish.yml