- name: Read variable definitions
  hosts: "*, localhost"
  roles:
    - read_config_vars

- name: Upgrade Cilium
  hosts: "{{ groups.master[0] }}"
  serial: 1
  tasks:
    - name: Kick Cilium upgrade
      ansible.builtin.include_tasks: roles/upgrade_cluster/tasks/cilium.yml